global using DataAccess.Data;
global using DataAccess.Models;
global using DataAccess.Requests;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
// global using ScriptureMemory.Server.DataAccess.Data;
global using ScriptureMemory.Server.DataAccess.Models;
global using ScriptureMemory.Server.Tools;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text.Json;
global using static ScriptureMemory.Server.Tools.Enums;