global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.EntityFrameworkCore.Migrations.Operations.Builders;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Azure.Core;
global using DataAccess.Data;
global using DataAccess.Models;
global using DataAccess.Requests;
global using DataAccess.Requests.UpdateRequests;
global using Microsoft.AspNetCore.Identity;
global using ScriptureMemory.Server.DataAccess.Data;
global using ScriptureMemory.Server.DataAccess.Models;
global using ScriptureMemory.Server.Tools;
global using System.Text.Json;
global using static ScriptureMemory.Server.Tools.Enums;