using Dapper;
using DataAccess.Data;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpLogging;
using Npgsql;
using Oracle.ManagedDataAccess.Client;
using ScriptureMemory.Server.DataAccess.Data;
using ScriptureMemory.Server.Services;
using ScriptureMemory.Server.Tools;
using System.Data;
using System.Text;
using VerseAppNew.Server.Bogus;
using VerseAppNew.Server.Services;
using Pgvector;

namespace ScriptureMemory.Server.Startup;

public static class Services
{
    /// <summary>
    /// Add authentication for Swagger
    /// </summary>
    /// <param name="services"></param>
    /// <returns></returns>
    public static IServiceCollection AddSwaggerGenWithAuth(this IServiceCollection services)
    {
        services.AddSwaggerGen(o =>
        {
            o.CustomSchemaIds(id => id.FullName!.Replace('+', '-'));

            var securityScheme = new Microsoft.OpenApi.Models.OpenApiSecurityScheme
            {
                Name = "JWT Authentication",
                Description = "Enter JWT",
                In = Microsoft.OpenApi.Models.ParameterLocation.Header,
                Type = Microsoft.OpenApi.Models.SecuritySchemeType.Http,
                Scheme = JwtBearerDefaults.AuthenticationScheme,
                BearerFormat = "JWT",
            };

            o.AddSecurityDefinition(JwtBearerDefaults.AuthenticationScheme, securityScheme);

            var securityRequirements = new Microsoft.OpenApi.Models.OpenApiSecurityRequirement
            {
                {
                    new Microsoft.OpenApi.Models.OpenApiSecurityScheme
                    {
                        Reference = new Microsoft.OpenApi.Models.OpenApiReference
                        {
                            Type = Microsoft.OpenApi.Models.ReferenceType.SecurityScheme,
                            Id = JwtBearerDefaults.AuthenticationScheme
                        },
                    },
                    []
                }
            };

            o.AddSecurityRequirement(securityRequirements);
        });

        return services;
    }

    /// <summary>
    /// Add authentication & authorization
    /// </summary>
    /// <param name="services"></param>
    /// <param name="configuration"></param>
    /// <returns></returns>
    public static IServiceCollection AddSecurity(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddAuthorization(o =>
        {
            o.AddPolicy("Admin", policy => policy.RequireClaim(
                "role", Enums.UserRole.Admin.ToString(), Enums.UserRole.SuperAdmin.ToString()));
            o.AddPolicy("SuperAdmin", policy => policy.RequireClaim(
                "role", Enums.UserRole.SuperAdmin.ToString()));
            o.AddPolicy("UserOnly", policy => policy.RequireClaim(
                "role", Enums.UserRole.User.ToString()));
            o.AddPolicy("UserOrAdmin", policy => policy.RequireClaim(
                "role", 
                Enums.UserRole.User.ToString(), 
                Enums.UserRole.Admin.ToString(), 
                Enums.UserRole.SuperAdmin.ToString()));
        }); 

        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(o =>
            {
                o.MapInboundClaims = false;
                o.RequireHttpsMetadata = false;
                o.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    IssuerSigningKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(configuration["Jwt:Secret"]!)),
                    ValidIssuer = configuration["Jwt:Issuer"],
                    ValidAudience = configuration["Jwt:Audience"],
                    ClockSkew = TimeSpan.Zero
                };
            });
        
        return services;
    }

    public static IServiceCollection AddServices(this IServiceCollection services, IConfiguration configuration)
    {
        //
        services.AddEndpointsApiExplorer();
        
        //
        services.AddSwaggerGenWithAuth();

        // Generate a Problem Details response to errors generated by middleware
        services.AddProblemDetails();

        //
        //SqlMapper.AddTypeHandler(new VectorTypeHandler());
        
        var connectionString = configuration.GetConnectionString("PostgresConnection")
            ?? throw new Exception("Connection string not found in configuration");
        
        // Add DbContext
        services.AddDbContextFactory<ApplicationDbContext>(
            options => options.UseNpgsql(connectionString, o => o.UseVector()));
        
        //
        services.AddHttpClient("ExpoPush", client =>
        {
            client.BaseAddress = new Uri("https://exp.host");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        });

        services.AddCors(options =>
        {
            options.AddDefaultPolicy(policy =>
            {
                policy.AllowAnyOrigin()
                      .AllowAnyHeader()
                      .AllowAnyMethod();
            });
        });

        services.AddControllers();
        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen();

        services.AddScoped<UserService>();
        services.AddScoped<AdminService>();
        services.AddScoped<EmailSenderService>();
        services.AddScoped<ActivityLogger>();
        services.AddScoped<PasswordResetService>();
        services.AddScoped<PopulateDatabase>();
        services.AddScoped<SearchService>();
        services.AddScoped<NotificationService>();
        services.AddScoped<VerseService>();
        //services.AddScoped<UserPassageService>();
        services.AddScoped<CollectionService>();
        services.AddScoped<TokenProvider>();
        services.AddScoped<VerseOfDayService>();

        services.AddScoped<VerseManagement>();
        services.AddScoped<BibleApi>();

        services.AddScoped<EmbeddingGenerator>();

        return services;
    }

    public static IServiceCollection AddDataAccess(this IServiceCollection services)
    {
        services.AddScoped<IRequestDbConnection, RequestDbConnection>();
        services.AddScoped<UserData>();
        services.AddScoped<AdminData>();
        services.AddScoped<UserSettingsData>();
        services.AddScoped<CrossReferenceData>();
        services.AddScoped<ActivityLoggingData>();
        services.AddScoped<SearchData>();
        services.AddScoped<NotificationData>();
        services.AddScoped<VerseData>();
        services.AddScoped<UserPassageData>();
        services.AddScoped<CollectionData>();
        services.AddScoped<PublishedCollectionData>();
        services.AddScoped<VerseOfDayData>();
        services.AddScoped<SessionData>();
        return services;
    }
}
